# Generated by Django 2.2.24 on 2021-11-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicsfollow',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
