# Generated by Django 2.2.24 on 2021-11-03 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_name', models.CharField(max_length=20)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('profile_hashtag', models.CharField(max_length=20)),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('tweet_content', models.CharField(max_length=200)),
                ('tweet_number', models.IntegerField()),
            ],
        ),
    ]
